### ISSUE TITLE
Enhance user interface

### ISSUE THREAD

**Issue by RubyaAfrin** [mitramir55/QA_app#1]
The user interface of the model could be enhanced and made it a bit more appealing. 
There exists some features described in this [paper ](https://dl.acm.org/doi/abs/10.1145/3335082.3335125) that can highlight the answer and create a better visualization so the user can navigate to that point of the article.

**Comment by mitramir55** [comment]
Hi Rubaya,

Thank you for the enhancement suggestion. I'm going to work on the appearance and visual effects in the following week. I will also add a few more pages that can explain each step to help the user understand what's happening, and will also add a few more links.
