### ISSUE TITLE
Specify the pages

### ISSUE THREAD

**Issue by RubyaAfrin** [mitramir55/QA_app#2]
1. I am not seeing any data in the "pages" folder. Could you please explain what is the purpose of this folder?
2. How many users in your application? What are the resources? 
3. Which page is dedicated for which user? Have you explained it within your code/documentation?

The above information is essential for new contributors to easily understand the overall work flow. Kindly add those documentation along with specific code comments in your _app.py_ file and link to README.md file.

**Comment by mitramir55** [comment]
1. The purpose of this folder is to have other pages that explain the app and the procedure. Can you contribute to the creation of those? If so, please make a pull request on the pages that I'll be creating.
2. The number of users is not defined. Resources will be added.
3. This type of info is available in the contributing file. For general users, though, there are explanations available on the README.md file.

Thanks
