### ISSUE TITLE
Running App

### ISSUE THREAD

**Issue by KaramveerSinghSidhu** [mitramir55/QA_app#4]
Hey, Just a quick question how do we run this application. Any special IDE, Library, etc. That we would need to get this work. We are looking to make integration tests for this repo.

**Comment by mitramir55** [comment]
Hi, 
to run it locally, you need to clone the project, install the requirements in the requirements.txt file, and then type `streamlit run app.py`. 
You can also go to the web app created on Streamlit. [Here](https://mitramir55-qa-app-app-yf272w.streamlitapp.com/) is the link.

**Comment by KaramveerSinghSidhu** [comment]
What is stream lit?

**Comment by mitramir55** [comment]
A library in Python. Please do a Google search to learn more.
