### ISSUE TITLE
Fix the license text in the code

### ISSUE THREAD

**Issue by minaoar** [mitramir55/QA_app#5]
Right now, the source code files contain license information with incorrect project owner name. It should be corrected with the name of this project owner 'Mitra Mirshafiee'.

> ![image](https://user-images.githubusercontent.com/5583535/198126015-f65535c8-75ea-4fb0-80aa-bf68493455b0.png)

> <img width="620" alt="image" src="https://user-images.githubusercontent.com/5583535/198126330-645287bf-6117-4e61-ad2a-b19b781ea9f4.png">

**Comment by mitramir55** [comment]
Thanks! Done.
