### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by KaramveerSinghSidhu** [mitramir55/QA_app#7]
Hey quick question as to what python version are you using because steamlit is causing us a lot of issues. Please asset.

**Comment by mitramir55** [comment]
Hi, I understand. I had some issues with Python version 3.9.7 too. I upgraded it to 3.9.13. I will also add a runtime.txt to make sure it's clear for others.

**Comment by KaramveerSinghSidhu** [comment]
============================= test session starts ==============================
platform linux -- Python 3.9.[13](https://github.com/CPSC2720-LAB-GRP/Lab4/actions/runs/3342511141/jobs/5534816806#step:5:14), pytest-7.2.0, pluggy-1.0.0
rootdir: /home/runner/work/Lab4/Lab4
collected 0 items / 1 error

==================================== ERRORS ====================================
_________________________ ERROR collecting test_app.py _________________________
test_app.py:2: in <module>
    from app.py import load_wiki_summary
app.py:5: in <module>
    import streamlit as st
/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/streamlit/__init__.py:48: in <module>
    from streamlit.proto.RootContainer_pb2 import RootContainer
/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/streamlit/proto/RootContainer_pb2.py:33: in <module>
    _descriptor.EnumValueDescriptor(
/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/google/protobuf/descriptor.py:755: in __new__
    _message.Message._CheckCalledFromGeneratedFile()
E   TypeError: Descriptors cannot not be created directly.
E   If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.[19](https://github.com/CPSC2720-LAB-GRP/Lab4/actions/runs/3342511141/jobs/5534816806#step:5:20).0.
E   If you cannot immediately regenerate your protos, some other possible workarounds are:
E    1. Downgrade the protobuf package to 3.[20](https://github.com/CPSC2720-LAB-GRP/Lab4/actions/runs/3342511141/jobs/5534816806#step:5:21).x or lower.
E    2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
E   
E   More information: https://developers.google.com/protocol-buffers/docs/news/20[22](https://github.com/CPSC2720-LAB-GRP/Lab4/actions/runs/3342511141/jobs/5534816806#step:5:23)-05-06#python-updates
=========================== short test summary info ============================
ERROR test_app.py - TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.[32](https://github.com/CPSC2720-LAB-GRP/Lab4/actions/runs/3342511141/jobs/5534816806#step:5:33)s ===============================

**Comment by KaramveerSinghSidhu** [comment]
Thats the error I keep getting im not sure what the protobuf is or how to upgrade it.

**Comment by mitramir55** [comment]
Could you please say how you run the app? You must be using the following command in the terminal when you're in the project's directory: streamlit run app.py

If you're doing this and getting an error, I suggest you update your packages with 
`conda update conda` and `conda update anaconda`, for instance, if you're using anaconda.
